require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

AllCops:
  Exclude:
    - './bin/*'
    - config/**/*
    - db/**/*
    - spec/**/*
    - vendor/**/*
  SuggestExtensions: false

